"""Create user settings table

Revision ID: 79897c5fc4bc
Revises: d015b7666886
Create Date: 2026-08-22 12:31:02.734654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79897c5fc4bc'
down_revision = 'd015b7666886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('budget_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('goal_reminders_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
